# This workflow will build a Quarkus project with Maven and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Jib-Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  QUARKUS_BUILD_OPTS:
    -Dquarkus.container-image.build=true
    -Dquarkus.container-image.push=true
    -Dquarkus.container-image.registry=ghcr.io
    -Dquarkus.container-image.group=${{ github.actor }}
    -Dquarkus.container-image.username=${{ github.actor }}
    -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }}
    -Dquarkus.jib.base-native-image=quay.io/quarkus/quarkus-distroless-image:1.0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.0.2

      - name: Cache local Maven repository
        uses: actions/cache@v3.0.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: GitHub Action for setting up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'

      - name: Build with Jib-Quarkus and Maven
        run: mvn -B package -Pnative $QUARKUS_BUILD_OPTS
